
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox
import sqlite3



OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/chanpanha/Desktop/survey/build/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def create_database():
    try:
        conn = sqlite3.connect("login.db")
        cursor = conn.cursor()

        # Create the "info" table (securely)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS info (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                username TEXT UNIQUE NOT NULL,
                password TEXT NOT NULL  -- Store hashed passwords
            )
        """)
        print("Database and table 'info' created successfully!")

        conn.commit()
        conn.close()
    except sqlite3.Error as e:
        print(f"Error creating database or table: {e}")
create_database()

def open_home():
    username = entry_1.get("1.0", "end-1c")
    password = entry_2.get("1.0", "end-1c")

    try:
        conn = sqlite3.connect("login.db")
        cursor = conn.cursor()

        # Check if username already exists
        cursor.execute("SELECT * FROM info WHERE username = ?", (username,))
        existing_user = cursor.fetchone()

        if existing_user:
            messagebox.showwarning("Warning", "Username already exists!")
        else:
            cursor.execute("INSERT INTO info (username, password) VALUES (?, ?)",
                           (username, password))
            conn.commit()
            messagebox.showinfo("Success", "Login credentials saved successfully!")
            
            # Destroy the current window and open gui1 (login successful)
            window.destroy()
            import gui1 

        conn.close()

    except sqlite3.Error as e:
        print(f"Error inserting data: {e}")
        messagebox.showerror("Error", "Failed to save credentials. Please try again.")

window = Tk()

window.geometry("1366x768")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 768,
    width = 1366,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    685.0,
    384.0,
    image=image_image_1
)

canvas.create_text(
    0.0,
    335.0,
    anchor="nw",
    text="*Password",
    fill="#1E1E1E",
    font=("Inter", 40 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    684.5,
    282.5,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=54.0,
    y=245.0,
    width=1261.0,
    height=73.0
)

canvas.create_text(
    0.0,
    177.0,
    anchor="nw",
    text="*Username",
    fill="#1E1E1E",
    font=("Inter", 40 * -1)
)
def gui14():
    import build.gui14 as gui14
    gui14.main()
    
    window.destroy()
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command= gui14,
    relief="flat"
)
button_1.place(
    x=873.0,
    y=542.1494140625,
    width=344.0,
    height=59.0
)

canvas.create_text(
    0.0,
    335.0,
    anchor="nw",
    text="*Password",
    fill="#1E1E1E",
    font=("Inter", 40 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    684.5,
    438.5,
    image=entry_image_2
)
entry_2 = Text(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=54.0,
    y=401.0,
    width=1261.0,
    height=73.0
)

canvas.create_rectangle(
    360.0,
    38.0,
    1045.0,
    158.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    629.0,
    62.0,
    anchor="nw",
    text="LOGIN",
    fill="#000000",
    font=("Inter Bold", 48 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=open_home,
    relief="flat"
)
button_2.place(
    x=520.912109375,
    y=592.1739501953125,
    width=332.1555480957031,
    height=75.69617462158203
)

button_2.config(command=open_home) 
window.resizable(False, False)
window.mainloop()
