
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from curses import window
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/chanpanha/Desktop/Survey/build/assets/frame14")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def main():
    window = Tk()

    window.geometry("1366x768")
    window.configure(bg = "#FFFFFF")


    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 768,
        width = 1366,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        750.0,
        81.0,
        image=image_image_1
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        699.5,
        195.5,
        image=entry_image_1
    )
    entry_1 = Text(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(
        x=223.5,
        y=163.0,
        width=952.0,
        height=63.0
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        699.5,
        308.0,
        image=entry_image_2
    )
    entry_2 = Text(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_2.place(
        x=223.0,
        y=276.0,
        width=953.0,
        height=62.0
    )

    entry_image_3= PhotoImage(
        file=relative_to_assets("entry_3.png"))
    entry_bg_3 = canvas.create_image(
        699.5,
        441.5,
        image=entry_image_3
    )
    entry_3 = Text(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_3.place(
        x=223.5,
        y=409.0,
        width=952.0,
        height=63.0
    )

    entry_image_4 = PhotoImage(
        file=relative_to_assets("entry_4.png"))
    entry_bg_4 = canvas.create_image(
        701.5,
        575.5,
        image=entry_image_4
    )
    entry_4 = Text(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_4.place(
        x=227.5,
        y=543.0,
        width=948.0,
        height=63.0
    )
def gui1():
    window.destroy()
    import gui1
    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=gui1,
        relief="flat"
    )
    button_1.place(
        x=535.0,
        y=639.0,
        width=396.0,
        height=78.0
    )

    canvas.create_text(
        200.0,
        371.0,
        anchor="nw",
        text="New Password *",
        fill="#FFFFFF",
        font=("Inter", 24 * -1)
    )

    canvas.create_text(
        211.0,
        233.0,
        anchor="nw",
        text="Current Password *",
        fill="#000000",
        font=("Inter", 24 * -1)
    )

    canvas.create_text(
        211.0,
        125.0,
        anchor="nw",
        text="Username *",
        fill="#000000",
        font=("Inter", 24 * -1)
    )

    canvas.create_text(
        200.0,
        503.0,
        anchor="nw",
        text="Confirm New Password *",
        fill="#FFFFFF",
        font=("Inter", 24 * -1)
    )
    window.resizable(False, False)
    window.mainloop()

if __name__ == '__main__':
    main()