
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import sqlite3
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/chanpanha/Desktop/survey/build/assets/frame4")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1366x768")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 768,
    width = 1366,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)
def gui1():
    window.destroy()
    import build.home as home
canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=gui1,
    relief="flat"
)
button_1.place(
    x=430.1708984375,
    y=32.0,
    width=427.0674133300781,
    height=70.63941192626953
)

canvas.create_text(
    551.0,
    671.0,
    anchor="nw",
    text="Submit",
    fill="#FFFFFF",
    font=("Inter Bold", 32 * -1)
)
def gui1():
    window.destroy()
    import build.home as home
button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=gui1,
    relief="flat"
)
button_2.place(
    x=471.0,
    y=669.0,
    width=373.0,
    height=76.0
)

canvas.create_text(
    87.0,
    121.0,
    anchor="nw",
    text="Doctor Name*",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    87.0,
    260.0,
    anchor="nw",
    text="ID *",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    87.0,
    399.0,
    anchor="nw",
    text="Specialization *",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    87.0,
    520.0,
    anchor="nw",
    text="Reason*",
    fill="#000000",
    font=("Inter", 24 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    674.5,
    207.0,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=103.0,
    y=174.0,
    width=1143.0,
    height=64.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    683.0,
    333.5,
    image=entry_image_2
)
entry_2 = Text(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=103.5,
    y=300.0,
    width=1159.0,
    height=65.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    683.0,
    472.0,
    image=entry_image_3
)
entry_3 = Text(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=103.0,
    y=439.0,
    width=1160.0,
    height=64.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    681.5,
    595.5,
    image=entry_image_4
)
entry_4 = Text(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=103.5,
    y=562.0,
    width=1156.0,
    height=65.0
)

def delete_doctor_info():
    try:
        conn = sqlite3.connect("doctor_info.db")
        cursor = conn.cursor()

        doctor_id = entry_2.get("1.0", "end-1c")  # Assuming entry_2 holds the Doctor ID
        if doctor_id.strip():  # Check if doctor_id is not empty
            cursor.execute("DELETE FROM dr_info WHERE doctor_id = ?", (doctor_id,))
            conn.commit()
            
            if cursor.rowcount > 0:  # Check if any rows were actually deleted
                messagebox.showinfo("Success", "Doctor information deleted successfully!")
                # Destroy the current window and open gui1 (login successful)
                window.destroy()
                import build.gui14 as gui14
                gui14.create_home_window()
            else:
                messagebox.showinfo("Not Found", "No doctor with that ID found.")
        else:
            messagebox.showerror("Error", "Please enter a Doctor ID.")

        conn.close()

    except sqlite3.Error as e:
        messagebox.showerror("Error", "Failed to delete doctor information.")
button_2.config(command=delete_doctor_info)
window.resizable(False, False)
window.mainloop()
