
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/chanpanha/Desktop/survey/build/assets/frame5")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1342x768")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 768,
    width = 1342,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    506.0,
    340.0,
    867.0,
    398.0,
    fill="#1AC40C",
    outline="")

canvas.create_rectangle(
    904.0,
    339.0,
    1244.0,
    397.0,
    fill="#FF0000",
    outline="")

canvas.create_rectangle(
    116.0,
    337.0,
    456.0,
    398.0,
    fill="#1400FF",
    outline="")
def gui6():
    window.destroy()
    import gui6
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command= gui6,
    relief="flat"
)
button_1.place(
    x=123.0,
    y=341.0,
    width=325.9452819824219,
    height=36.37914276123047
)
def gui7():
    window.destroy()
    import gui7
button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=gui7,
    relief="flat"
)
button_2.place(
    x=532.0,
    y=343.0,
    width=315.0,
    height=35.0
)
def gui9():
    window.destroy()
    import gui9
button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=gui9,
    relief="flat"
)
button_3.place(
    x=916.0,
    y=342.0,
    width=315.0,
    height=36.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    686.0,
    160.0,
    image=image_image_1
)

def open_home():
    window.destroy()
    import build.home as home
button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=open_home,
    relief="flat"
)
button_4.place(
    x=621.0,
    y=468.0,
    width=196.0,
    height=203.02484130859375
)
window.resizable(False, False)
window.mainloop()
