
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/chanpanha/Desktop/survey/build/assets/frame8")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1366x768")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 768,
    width = 1366,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)
def gui1():
    window.destroy()
    import build.home as home
canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=gui1,
    relief="flat"
)
button_1.place(
    x=481.0,
    y=668.0,
    width=194.0,
    height=55.0
)
def gui1():
    window.destroy()
    import build.home as home
button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=gui1,
    relief="flat"
)
button_2.place(
    x=715.0,
    y=668.0,
    width=194.0,
    height=55.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    677.0,
    100.0,
    image=image_image_1
)

canvas.create_text(
    116.0,
    240.0,
    anchor="nw",
    text="Enter New Patient’s Name*",
    fill="#000000",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    116.0,
    371.0,
    anchor="nw",
    text="Enter New Patient ID*",
    fill="#000000",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    116.0,
    522.0,
    anchor="nw",
    text="Enter New Medical History*",
    fill="#000000",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    780.0,
    240.0,
    anchor="nw",
    text="Enter New Date of Birth*",
    fill="#000000",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    780.0,
    371.0,
    anchor="nw",
    text="Enter New Contact Information*",
    fill="#000000",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    780.0,
    517.0,
    anchor="nw",
    text="Enter New Assigned Doctor*",
    fill="#000000",
    font=("Inter", 20 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    359.5,
    307.0,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=120.0,
    y=274.0,
    width=479.0,
    height=64.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    1031.5,
    307.0,
    image=entry_image_2
)
entry_2 = Text(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=792.0,
    y=274.0,
    width=479.0,
    height=64.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    1031.5,
    438.0,
    image=entry_image_3
)
entry_3 = Text(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=792.0,
    y=405.0,
    width=479.0,
    height=64.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    1031.5,
    589.0,
    image=entry_image_4
)
entry_4 = Text(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=792.0,
    y=556.0,
    width=479.0,
    height=64.0
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    359.5,
    438.0,
    image=entry_image_5
)
entry_5 = Text(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=120.0,
    y=405.0,
    width=479.0,
    height=64.0
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    371.5,
    589.0,
    image=entry_image_6
)
entry_6 = Text(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_6.place(
    x=132.0,
    y=556.0,
    width=479.0,
    height=64.0
)
window.resizable(False, False)
window.mainloop()
