
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import sqlite3
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/chanpanha/Desktop/survey/build/assets/frame9")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1366x768")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 768,
    width = 1366,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    544.0,
    670.0,
    anchor="nw",
    text="Submit",
    fill="#FFFFFF",
    font=("Inter Bold", 32 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    643.171142578125,
    67.0,
    image=image_image_1
)

canvas.create_text(
    66.0,
    120.0,
    anchor="nw",
    text="Patient’s Name*",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    104.0,
    258.0,
    anchor="nw",
    text="Patient’s ID *",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    103.0,
    396.0,
    anchor="nw",
    text="Reason *",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    46.0,
    512.0,
    anchor="nw",
    text="Are you sure? Once you cancel the appointment, you can’t go back*. Enter Yes or NO",
    fill="#000000",
    font=("Inter", 20 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    693.0,
    190.0,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=99.0,
    y=157.0,
    width=1188.0,
    height=64.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    684.0,
    331.0,
    image=entry_image_2
)
entry_2 = Text(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=81.0,
    y=298.0,
    width=1206.0,
    height=64.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    684.0,
    468.5,
    image=entry_image_3
)
entry_3 = Text(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=81.5,
    y=435.0,
    width=1205.0,
    height=65.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    685.5,
    584.5,
    image=entry_image_4
)
entry_4 = Text(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=84.5,
    y=551.0,
    width=1202.0,
    height=65.0
)
def gui1():
    window.destroy()
    import build.home as home
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=gui1,
    relief="flat"
)
button_1.place(
    x=464.0,
    y=668.0,
    width=373.0,
    height=76.0
)

canvas.create_text(
    999.0,
    650.0,
    anchor="nw",
    text="Submit",
    fill="#FFFFFF",
    font=("Inter Bold", 32 * -1)
)
def delete_patient_info():
    try:
        conn = sqlite3.connect("add_patient.db")  # Connect to your database
        cursor = conn.cursor()

        patient_name = entry_1.get("1.0", "end-1c").strip()  # Assuming entry_1 is for Patient Name
        patient_id = entry_2.get("1.0", "end-1c").strip()   # Assuming entry_2 is for Patient ID
        reason = entry_3.get("1.0", "end-1c").strip()      # Assuming entry_3 is for Reason

        # Build dynamic SQL query based on entered data
        where_clause = []
        params = []

        if patient_name:
            where_clause.append("patient_name = ?")
            params.append(patient_name)
        if patient_id:
            where_clause.append("patient_id = ?")
            params.append(patient_id)
        
        if not where_clause:
            messagebox.showerror("Error", "Please enter at least patient name or ID.")
            return  # Exit function if no criteria provided

        where_clause = " AND ".join(where_clause)
        sql = f"DELETE FROM add_patient_info WHERE {where_clause}"

        cursor.execute(sql, tuple(params))  # Execute the query
        conn.commit()  # Commit changes to make the deletion permanent

        if cursor.rowcount > 0:
            messagebox.showinfo("Success", "Patient information deleted successfully!")
            # Destroy the current window and open gui1 (login successful)
            window.destroy()
            import build.gui14 as gui14
            gui14.create_home_window()
        else:
            messagebox.showinfo("Not Found", "No patient found matching the criteria.")

        conn.close()
    except sqlite3.Error as e:
        print(f"Error deleting data: {e}")
        messagebox.showerror("Error", f"Database error: {e}")
button_1.config(command=delete_patient_info) 
window.resizable(False, False)
window.mainloop()
